app:
  jwt-issuer: Cookbook Application
  jwt-expiration-milliseconds: 604800000
  jwt-secret: GZJ3K4M6P7Q8SATBUDWEXFYH2J3K5N6P7R9SATCVDWEYGZH2K4M5N7Q8R
server:
  error:
    include-stacktrace: never
  servlet:
    session:
      cookie:
        http-only: false
        secure: true
spring:
  datasource:
    password: Aa2115725
    url: jdbc:postgresql://localhost:5432/cookbook
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: false
  security:
    user:
      name: peerawit
      password: 1234
